<?php
/**
 *
 * @file ajax test
 *
 */
function ajax_test2_menu() {
$items['ajax_test2/linktest'] = array(
  'title' => 'linktest',
  'page callback' => 'ajax_link_page',
  'access arguments' => array('access content'),
  'type' => MENU_NORMAL_ITEM, 
);

$items['my-ajax-test/%'] = array(
  'title' => 'Ajax test callback',
  'page callback' => 'ajax_link_callback',
  'page arguments' => array(1),
  'access arguments' => array('access content'),
  'type' => MENU_NORMAL_ITEM, 
);

return $items;  
}
function ajax_link_page() {
return array(
  '#type' => 'link',
  '#title' => 'Ajax link',
  '#href' => 'my-ajax-test/nojs',
  '#prefix' => '<div id="ajax-link">',
  '#suffix' => '</div><div id="ajax-display"></div>',
  '#ajax' => array(
    'effect' => 'fade',
  ),
);
}
function ajax_link_callback($ajax) {
drupal_add_library('system', 'drupal.ajax');

$time = t('current time is : !time', array('!time' => date('Y-m-d H:i:s')));
if ($ajax == 'ajax') {
  $command = array();
   // Ajax command to replace the #ajax-display element with the current time. 
  
  $command[] = ajax_command_replace("ajax-display", "<div id='ajax-display'>" + $time +"</div>"); 
  
 // Add a visual "changed" marker to the '#ajax-display' element.
  $command[] = ajax_command_changed('ajax-link');
  
  // Trigger our ajax_link jQuery plugin.
  
  $commands[] = ajax_command_invoke(NULL, "ajax_link");
  // Menu 'page callback' and #ajax['callback'] functions are supposed to
    // return render arrays. If returning an Ajax commands array, it must be
    // encapsulated in a render array structure.
  ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
  
} 
else {
  return array('#markup' => $time);
}
}
function ajax_test2_theme() {
  return array(
    'ajax_test2' => array(
      'message' => 'i came from ajax_test2 module themeing functions'),
  );
}

/**
hook_preprocess_node() {
}
*/
